# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bitter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bitter

  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'
  pod 'KeychainAccess'
  pod 'HandyJSON'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

end
